### PR TITLE
Feature/ Add VAction Unit tests

### PR DESCRIPTION
**Pull request by ontoneio**
- Adds some unit tests for `VAction` component
- Minor formatting fixes in `VBreadcrumbs` component to be able to commit.

### CODE REVIEW

**Comment by ontoneio** [comment]
Hmmm, any advice on merge strategy?

Perhaps we should start squash merging? 

I didn't realize I was pushing these same commit histories.

**Comment by AustinGil** [comment]
Yeah, I've been squashing the other ones. Not sure why this one still has the old history.

**Comment by AustinGil** [comment]
Have you re-merged from `develop` since you branched?

**Comment by ontoneio** [comment]
Yeah, I pulled and remerged into my branch. I can see evidence in the bumped version in `package.json`.
So not sure why. Let me close this and I will figure it out tomorrow.

**Pull request closed without merging**
